### PR TITLE
Fixes for `make install`

### PR DESCRIPTION
**Pull request by joshgav**
- Change target path for x86_64 install to work on Ubuntu.
- Added "dist" and "install" options to `./scripts/build_and_test.sh`

### CODE REVIEW

**Comment by joshgav** [comment]
@v-vlshch can you take a look and see what the proper target should be for CentOS and OpenSUSE? For Ubuntu it's `/usr/lib/x86_64-linux-gnu`. More info in the [spec](https://wiki.ubuntu.com/MultiarchSpec).

We may need conditionals depending on the distro.

**Comment by vladimir-shcherbakov** [comment]
when I tested **make install** on target OS 
- for Ubuntu 64 bit option **target.path += /usr/lib** was enough but is worked with **target.path = /usr/lib64** as well.
- for  CentOS and openSUSE I had to specify **target.path = /usr/lib64** for 64 bit version.

**Comment by joshgav** [comment]
`/usr/lib64` didn't work for on Ubuntu 15.04. Can you add conditionals to the .pro file which rely on `uname -a` or `lsb_release -a`? Even if for now they point to the same directory. An example is [here](http://stackoverflow.com/questions/10093643/how-to-create-distro-specific-conditional-qmake-project).

And perhaps we should put this shared configuration in a shared .pro file and include it where needed using `include(shared_config.pro)` or similar.

Thanks!

**Comment by joshgav** [comment]
And perhaps we should put this shared configuration in a shared .pro file and include it where needed using `include(shared_config.pro)` or similar.

**Pull request closed without merging**
